---
- name: show
  hosts: acx_switch
  collections:
    - arubanetworks.aoscx
  tasks:
    - name: Check version
      aoscx_command:
        commands: 
          - 'config'
          - 'vlan 2'
          
        
