---
- hosts: 2930fsb5scata
  collections:
    - arubanetworks.aos_switch
  tasks:
  - name: upload image
    arubaoss_command:
      commands: 
        - copy tftp flash 10.210.210.251 WC_16_08_0014.swi primary
        - y
      timeout: 120
  - name: copy flash flash secondary
    arubaoss_command:
      commands: copy flash flash secondary
  - name: boot
    arubaoss_reboot:
      boot_image: BI_PRIMARY_IMAGE
      is_wait: False
      
