---
- hosts: 3810M
  vars:
    ansible_become: yes
    ansible_become_method: enable
  tasks:
  - name: test config module
    arubaoss_config:
      lines:
        snmp-server community cosc_7384 operator